### ISSUE TITLE
Gracefully abort if YAML file ends in "---"

### ISSUE THREAD

**Issue by olitheolix** [olitheolix/square#18]
The following YAML snippet causes an error (notice the `---` at the end):

```
apiVersion: v1
kind: Namespace
metadata:
  name: default
spec:
  finalizers:
  - kubernetes
---
```

Gracefully intercept this error, write a log message, then abort the program.
